### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by cmanjunathan45** [shubham1710/Youtube-downloader#3]
I have paste the video link... while processing the link .it will return A value error like this  how to fix this 
I reinstall the package too but still this error returns ...
**Traceback (most recent call last):
  File "abc.py", line 3, in <module>
    you=YouTube(link)
  File "/usr/local/lib/python3.8/dist-packages/pytube/__main__.py", line 92, in __init__
    self.descramble()
  File "/usr/local/lib/python3.8/dist-packages/pytube/__main__.py", line 140, in descramble
    apply_signature(self.player_config_args, fmt, self.js)
  File "/usr/local/lib/python3.8/dist-packages/pytube/extract.py", line 225, in apply_signature
    cipher = Cipher(js=js)
  File "/usr/local/lib/python3.8/dist-packages/pytube/cipher.py", line 31, in __init__
    var, _ = self.transform_plan[0].split(".")
ValueError: too many values to unpack (expected 2)
![pytuberror](https://user-images.githubusercontent.com/67182077/88669327-60f40a00-d101-11ea-84f0-85c140996389.png)
**

**Comment by shubham1710** [comment]
Can you please show me the code you wrote?

**Comment by shubham1710** [comment]
Yes, this was an issue as Youtube changed their Javascript so now this no longer works.

So, you need to install pytubeX to fix this issue. Its the new pytube3 update.
Code will remain same.

Just do:
pip install pytubeX
